### ISSUE TITLE
Add TENSORFLOW

### ISSUE THREAD

**Issue by phd84** [rationalmatter/Juno-Issue-Tracker#255] opened 2021-06-20 05:44 UTC
**What is the name of the package?**
A name or link to the Python package you think should be pre-installed in Juno. Mind that you can install pure Python packages from PyPI in Juno — those that can be successfully installed won't be embedded in the app.

**Comment by navoshta** [comment] 2021-06-21 11:54
Closing as a duplicate of #39 — I know it's been a while, but including TF is an ambitious project, which I haven't got to yet I'm afraid.

**Closed by navoshta** 2021-06-21 11:54 UTC
Labels: Juno, package
