### ISSUE TITLE
Juno App Crashing

### ISSUE THREAD

**Issue by MrJaba** [rationalmatter/Juno-Issue-Tracker#230] opened 2021-01-05 21:20 UTC
**Describe the bug**
Juno Crashing, and also an incident of hanging. 
I've had Juno crash about 5 times in 2 days of use in different scenarios. 

Scenario 1: Outright crash. The application has been moved from a background app to a foreground app in split screen mode with Apple Books. This has caused a crash twice, and a complete hang once (app had to be killed and then restarted). I've noticed that when it moves from background to foreground that it goes through the loading screen and has to restart the kernel as well which is irksome but not too big of a deal. 

Scenario 2: Trying to insert an image via the command palette. Trying to insert an image (with 1 other image successfully in the notebook) the dialog to choose an image doesn't display at all. Trying this 2/3 times and then another action for instance changing the cell type to markdown will cause the application to crash. This has happened twice in a row. 

**To Reproduce**
Scenario 1:
Switch between apps and at random it will crash. 
Scenario 2:
1. Go to notebook
2. CMD-Shift P to open command palette
3. Type insert image
4. Note missing image picker (cell is code cell)
5. Repeat a few times
6. Try to change cell to markdown
7. App crashes. 

**Expected behavior**
Scenario 1: App to not crash. 
Scenario 2: App to not crash, but also indicate that the image picker isn't being displayed because the cell type is incorrect.

**Screenshots**
Sorry, it's not every time so I don't have a recording. 

**Environment (please complete the following information):**
 - Device: IPad Pro 2020 12.9" 4th Generation With Magic Keyboard
 - iOS version: 14.2
 - App version: 1.2.8 (5549)

**Comment by navoshta** [comment] 2021-01-08 17:31
Thank you for the detailed steps @MrJaba, this is very helpful! I will need to look a bit closer into this, thanks for reporting.

**Comment by navoshta** [comment] 2021-04-19 09:23
Hi @MrJaba — crash in Scenario 1 should be (hopefully) fixed, or at least appear way less frequent in the recent Juno beta releases, please let me know if you would like to give it a go, and I will add you to our TestFlight (I may need your email address, so you can ping me at beta@juno.sh).

As per insert image dialogue, I couldn't reproduce this crash I'm afraid. Do you get it every time with these steps, or only occasionally?

**Comment by alexstaravoitau** [comment] 2023-04-22 12:17
Hopefully, this should have been fixed by now with Juno's 2.0 and 2.1 releases (2.1 is now live on App Store).

**Closed by alexstaravoitau** 2023-04-22 12:17 UTC
Labels: bug, Juno
