### ISSUE TITLE
Cannot install regex package

### ISSUE THREAD

**Issue by xandorlv** [rationalmatter/Juno-Issue-Tracker#199] opened 2020-08-08 14:14 UTC
**Describe the bug**
Search for regex in packages, try to install, get error.

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"]
 - iOS version: [e.g. iOS 12.2]
 - App version [e.g. 1.0.0]

**Comment by navoshta** [comment] 2020-08-14 14:00
Thanks for reporting — closing this as a duplicate of #178 package request.

**Closed by navoshta** 2020-08-14 14:00 UTC
