### ISSUE TITLE
cannot open ipynb files

### ISSUE THREAD

**Issue by digitaldust** [rationalmatter/Juno-Issue-Tracker#233] opened 2021-01-06 14:52 UTC
I have some ipynb files on google drvie that I open and modify using VSCode on my macbook. When I try to access them from Juno, all I see is a greyed file without any icon, and Juno won't open it.

I don't have any other programming app on my iPad.

I am running an iPad Pro 4 gen, with iOS 14.2

**Comment by digitaldust** [comment] 2021-01-06 17:53
It might be related to issues with Google Drive, I cannot create notebook from Juno when I am in Drive, I get the error below:

Fail to open notebook 
The operation couldn’t be completed. 
(com.apple.DocumentManager error 1)

**Comment by navoshta** [comment] 2021-01-08 17:30
Hi @digitaldust — yes looks like Google Drive doesn't integrate well with the iOS's Files app, and for some reason doesn't let 3rd party apps edit .ipynb file format. I'll close this issue as a duplicate of #96, as this also seems to be Google Drive related. 

Ideally, Google would fix this in their iOS integration, but I do plan to look into alternative approaches as well (as there are other, even though less restricting, limitations with Dropbox, for example).

**Closed by navoshta** 2021-01-08 17:30 UTC
Labels: Juno, bug
