### ISSUE TITLE
cannot load from Googledrive

### ISSUE THREAD

**Issue by AG4GitHub** [rationalmatter/Juno-Issue-Tracker#124] opened 2020-01-18 13:05 UTC
**Cannot open Notebook from Google Drive**

I tried to open or import a notebook and related resources from Google drive.

Navigated to the relevant folder ; but none of the files can be selected; all greyed out. only folders are selectable.

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem
![73655316-D600-485E-B602-583982B80338](https://user-images.githubusercontent.com/8003258/72664194-f8cbb980-3a35-11ea-8152-19d9a0af4a1b.png)
.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"] iphone 7plus
 - iOS version: [e.g. iOS 12.2] 13.3
 - App version [e.g. 1.0.0]

**Comment by navoshta** [comment] 2020-01-21 20:41
Yep unfortunately Google Drive file provider doesn't work with custom UTIs declared by other apps (e.g. Juno). Not sure why they chose to implement it that way I'm afraid, but I'm going to look into possible workarounds, if there are any on the app side of things.

Closing this issue as a duplicate of #96.

**Closed by navoshta** 2020-01-21 20:41 UTC
Labels: Juno Connect, bug
