### ISSUE TITLE
Package installer is not present for use

### ISSUE THREAD

**Issue by mmymoney** [rationalmatter/Juno-Issue-Tracker#213] opened 2020-10-25 05:32 UTC
**Describe the bug**

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"]
 - iOS version: [e.g. iOS 12.2]
 - App version [e.g. 1.0.0]

**Comment by navoshta** [comment] 2020-10-30 15:57
Apologies @mmymoney, I'm not sure I understand what is exactly the issue with the package installer. Could you please explain further? Perhaps you have a screenshot of what exactly doesn't work as you expect?

**Comment by alexstaravoitau** [comment] 2022-03-22 10:11
Closing as a possible duplicate of #42 — Juno 1.5 comes with a package manager, which (hopefully) resolves some of the package management frustration.

**Closed by alexstaravoitau** 2022-03-22 10:11 UTC
Labels: Juno
