### ISSUE TITLE
Add Tensorflow.keras

### ISSUE THREAD

**Issue by mattabott** [rationalmatter/Juno-Issue-Tracker#256] opened 2021-06-26 21:21 UTC
Please add the Tensorflow.keras extension. It could be very useful for machine learning!

**Comment by navoshta** [comment] 2021-06-29 15:55
Thanks for reporting @mattabott — I'll close this as a duplicate of #8. When there is any progress with Keras, I'll make sure to update the original issue.

**Closed by navoshta** 2021-06-29 15:55 UTC
Labels: Juno, enhancement

**Comment by mattabott** [comment] 2021-06-30 23:01
Thank you!
