### ISSUE TITLE
Packages installed disappeared after a while without using

### ISSUE THREAD

**Issue by enochling** [rationalmatter/Juno-Issue-Tracker#141] opened 2020-03-28 18:09 UTC
**Describe the bug**
I installed several packages via the built in installer. Yet after quitting Juno app for a while (like switching to other apps and opening Juno app again with logo loading), the packages installed were gone and I needed to install again.
**Expected behavior**
I suppose it was designed to have installed packages stayed as they are. installing the packages one by one every time open Juno is very tedious
**Environment (please complete the following information):**
 - Device: [iPad Pro 1st gen)
 - iOS version: [iPadOS 13.4
 - App version [latest version to date

**Comment by navoshta** [comment] 2020-03-30 16:11
@enochling Yep, installed packages shouldn't disappear, of course. Are these packages' files actually gone from _/site-packages_ directory, as in, you can't import them in notebooks?

Please, mind that Juno's package installer doesn't keep track of previously installed packages; it will install replacing whatever is currently already in _/site-packages_ (see [here](https://juno.sh/juno-pypi-package-installer/#removing-packages)). So even if a package is already installed, package installer will _not_ display it as installed if you search for it after installing previously. We do plan to let it keep track of packages in future though, see #42.

**Comment by alexstaravoitau** [comment] 2022-03-22 10:12
Closing as a possible duplicate of #42 — Juno 1.5 comes with a package manager, which (hopefully) resolves some of the package management frustration.

**Closed by alexstaravoitau** 2022-03-22 10:12 UTC
Labels: bug, Juno
