### ISSUE TITLE
Could not open .ipynb file from Google drive

### ISSUE THREAD

**Issue by WeijieChen-Helsinki** [rationalmatter/Juno-Issue-Tracker#125] opened 2020-01-18 17:43 UTC
I am using Juno to open .ipynb file in google drive or wherever Juno allows to store. All failed to be opened.  

I checked other threads before, there were no other programming apps installed. Neither my iPhone or iPad works. I am using IPhone 6s Plus, and iPad Air 2.

![239A3B6B-5173-40CA-9EA2-5A79078A5765](https://user-images.githubusercontent.com/59842360/72667956-b4362300-3a21-11ea-9324-c916f578c56f.png)

**Environment (please complete the following information):**
 - Device:  iPad Air 2 
 - iOS version:  iOS 13
 - App version 1.1.1

**Comment by navoshta** [comment] 2020-01-21 20:40
Yep unfortunately Google Drive file provider doesn't work with custom UTIs declared by other apps (e.g. Juno). Not sure why they chose to implement it that way I'm afraid, but I'm going to look into possible workarounds, if there are any on the app side of things.

Closing this issue as a duplicate of #96.

**Closed by navoshta** 2020-01-21 20:40 UTC
Labels: Juno, bug
