### ISSUE TITLE
Cannot rename new or existing notebooks

### ISSUE THREAD

**Issue by jonbjornn** [rationalmatter/Juno-Issue-Tracker#119] opened 2020-01-09 16:14 UTC
**Describe the bug**
When creating a brand new notebook, or attempting to rename an existing one, Juno gives an error with the file path:

Example: 
Error renaming file: private/var/mobile/Containers/Data/Application/C8234672-AAC5-45E7-91FE-1173C58C9240/Documents/Local data/Untitled.ipynb

**To Reproduce**
Simple to reproduce, I haven’t yet been able to rename a notebook successfully. This has been attempted within Juno’s own app folder in the “On My iPhone” local space.

**Expected behavior**
The app to rename the file and do as it’s told 😄

**Screenshots**
![Screenshot 2020-01-09 at 8 09 12 AM](https://user-images.githubusercontent.com/6331668/72084194-e922d700-32b7-11ea-9a62-9fbd0cf6d1d5.png)

**Environment (please complete the following information):**
iPhone 11 Pro Max
iOS 13.3.1
Juno 1.1.1 (4128)

**Comment by arumihsok** [comment] 2020-01-09 20:03
I have a similar bug. I can't rename while I am editing a notebook, but I can rename if I am located on the file manager.
My device is iPad (7th generation) running iPadOS 13.3.

**Comment by navoshta** [comment] 2020-01-11 23:40
Thanks for reporting @jonbjornn, @arumihsok! I'll close this issue as a duplicate of #56. 

Please, use file browser for renaming notebook for the time being; next Juno release will either have this fixed or at least renaming from notebook editor disabled.

**Closed by navoshta** 2020-01-11 23:40 UTC
Labels: Juno, bug
