### ISSUE TITLE
No es posible sacar tu proprio archivo de texto del environment

### ISSUE THREAD

**Issue by AmePelliccia** [rationalmatter/Juno-Issue-Tracker#414] opened 2024-07-13 17:12 UTC
**Describe the bug**

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Environment (please complete the following information):**
 - Device: [e.g. iPad Pro 11"]
 - iOS version: [e.g. iOS 12.2]
 - App version [e.g. 1.0.0]

**Comment by alexstaravoitau** [comment] 2024-07-21 16:31
Sounds like a duplicate of #46, feel free to reopen otherwise.

**Closed as completed by alexstaravoitau** 2024-07-21 16:31 UTC
Labels: bug, Juno Connect
