### ISSUE TITLE
Package installed hangs

### ISSUE THREAD

**Issue by tlockney** [rationalmatter/Juno-Issue-Tracker#41] opened 2019-09-08 07:14 UTC
**Describe the bug**
After installing a package, the dialog box won't close. It lets me search for other packages, but it redraws the package name over the previous package name.

**To Reproduce**
1. Open package installer
2. Search for 'requests'
3. Install package
4. Attempt to select "close" button.

**Expected behavior**
The dialog box should be closeable.

**Screenshots**
![63400E94-7CA7-4983-B026-AF535ED36629](https://user-images.githubusercontent.com/8944/64484890-73a1df80-d1cd-11e9-8a37-1acfa65b736f.png)

**Environment (please complete the following information):**
 - Device: iPad Pro 10.5"
 - iOS version: iOS 13
 - App version e.g. 1.0.4 (3858)

**Comment by ndfred** [comment] 2019-09-08 09:21
Same for me on iPhone when searching for a package and eventually not wanting to install it, I have to kill the app because the Done button won’t work

**Comment by ndfred** [comment] 2019-09-08 09:24
I was actually searching for the requests package too, which really should be included as standard given how popular it is (I even thought it was standard with python 3)

**Comment by navoshta** [comment] 2019-09-08 15:47
Thanks, I will look into this.

> I was actually searching for the requests package too, which really should be included as standard given how popular it is

@ndfred — that's a good point, although I'm in two minds about this. I agree that it would be convenient to include something that is very popular (and what most users will install anyway). On the other hand, I wanted to embed as few things as possible, because I don't allow upgrading packages that are pre-installed (yet). This is to make sure users don't accidentally override a module which is necessary for the app itself to function. So, by embedding a package I essentially "lock" its version, which some users would not like either, if a new package version is released.

**Comment by ndfred** [comment] 2019-09-08 22:54
One of the reasons I was surprised I couldn't use requests out of the box is that Azure Workbooks have them by default. Might be worth digging up their standard list of packages and offering that as an add-on, or installing all of these on first launch.

Since you control the runtime, how about you suggest installing a package the first time it is required then, or if you detect an import error?

I understand that modifying built-in packages that the app's code relies on could wreak havoc. A potential solution there might be to release an update to the app every time a built-in package gets an update.

Finally I would assume the current "package management" strategy is to download an egg and decompress it without dealing with dependencies? Do you have plans to eventually customize + embed pip or something similar to get full dependencies support?

**Comment by navoshta** [comment] 2019-09-30 12:14
Turns out this is an iOS 13.1 bug, which unfortunately is still reproducible in iOS 13.1.1: http://www.openradar.me/7194998

Juno 1.1 has a workaround, which I will disable once this issue is (hopefully) fixed in subsequent iOS releases.

**Closed by navoshta** 2019-09-30 12:14 UTC
Labels: Juno, bug
