### ISSUE TITLE
Add **cvxpy**

### ISSUE THREAD

**Issue by AbedTakriti** [rationalmatter/Juno-Issue-Tracker#348] opened 2023-03-13 17:53 UTC
**CVXPY https://www.cvxpy.org/ **
A name or link to the Python package you think should be pre-installed in Juno. Mind that you can install pure Python packages from PyPI in Juno — those that can be successfully installed won't be embedded in the app.

**Comment by alexstaravoitau** [comment] 2023-03-22 15:47
Closing as a duplicate of #170

**Closed as completed by alexstaravoitau** 2023-03-22 15:47 UTC
Labels: package, Juno
