### ISSUE TITLE
Add **opencv**

### ISSUE THREAD

**Issue by Haliturey** [rationalmatter/Juno-Issue-Tracker#369] opened 2023-10-14 11:02 UTC
I can find “opencv” on pypi but Juno couldn’t see this package in app. By the way I couldn’t add “opencv” to June via manually. I have a project and I couldn’t work for missing packages. Could you please solve it urgently ?

**Comment by alexstaravoitau** [comment] 2023-10-16 13:07
Thanks for reporting @Haliturey — I'll close this issue as a duplicate of #109. OpenCV is a popular request, and we will be looking into adding it to Juno very soon.

**Closed as completed by alexstaravoitau** 2023-10-16 13:07 UTC
Labels: package, Juno
