### ISSUE TITLE
Composite actions from “Jupyter Commands” does not work as intended

### ISSUE THREAD

**Issue by afedotov** [rationalmatter/Juno-Issue-Tracker#282] opened 2021-10-17 19:15 UTC
**Describe the bug**

When using these composite actions from “Jupyter Commands” combobox:

- [Confirm] restart kernel and clear output
- [Confirm] restart kernel and run all cells

Only first action “restart kernel” is executed, ignoring following “clear output” and “run all cells”

**To Reproduce**
Steps to reproduce are straightforward:
1. Open any notebook
2. Tap on notebook name to open notebook menu
3. Select “Jupyter Commands”
3. Scroll down and execute any of mentioned composite actions
4. Observe that second action is not executed

**Expected behavior**
Both actions from composite must be executed.

**Environment:**
 - Device: iPad Pro 11" 2nd gen (2020), without hw keyboard, dark mode
 - OS version: iPadOS 15.0.2
 - App version: 1.3.14 (6557)

**Comment by alexstaravoitau** [comment] 2021-10-25 18:28
Thanks for reporting @afedotov — yep I can confirm these are not working right now, which seems to be related to how kernel management is handled in Juno. I will look into this.

**Comment by alexstaravoitau** [comment] 2023-04-22 11:55
Should be addressed in Juno 2.0 and 2.1 releases (now live on App Store).

**Closed as completed by alexstaravoitau** 2023-04-22 11:55 UTC
Labels: bug, Juno
